services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - orquestador
    networks:
      - app_network

  orquestador:
    build: ./orquestador
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: '10905114lp'
      DB_NAME: 'GESTOR_ELECTRIC'
      INVENTARIO_SERVICE_URL: http://inventario:3001
    networks:
      - app_network


  autenticacion:
    build: ./servicios/autenticacion
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy  # Esperar a que PostgreSQL pase el healthcheck
    environment:
      DATABASE_URL: postgres://postgres:10905114lp@postgres:5432/GESTOR_ELECTRIC

    networks:
      - app_network

  inventario:
    build: ./servicios/inventario  # <--- ruta del microservicio
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: '10905114lp'
      DB_NAME: 'GESTOR_ELECTRIC'
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '10905114lp'
      POSTGRES_DB: 'GESTOR_ELECTRIC'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:   # <---- SE AGREGA ESTO
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:

networks:
  app_network:
