
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      orquestador:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - VITE_API_BASE_URL=/api

  orquestador:
    build: ./orquestador
    ports:
      - "5000:5000"
    depends_on:
      postgres_db:
        condition: service_healthy
      portal:
        condition: service_started
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: gestor_nuevo
      NODE_ENV: development
      PORTAL_SERVICE_URL: http://portal:5100
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]  # Probamos con el endpoint principal
      interval: 10s
      timeout: 5s
      retries: 5

  autenticacion:
    build: ./servicios/autenticacion
    ports:
      - "5001:5001"
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:123456@postgres_db:5432/gestor_nuevo
    networks:
      - app_network

  portal:
    build: ./servicios/portal
    ports:
      - "5100:5100"
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: gestor_nuevo
      NODE_ENV: development
    volumes:
      - ./servicios/portal:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - postgres_db
  temas:
    build: ./servicios/temas
    ports:
      - "5200:5200"
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: gestor_nuevo
    networks:
      - app_network
    depends_on:
      - postgres_db
      
  postgres_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gestor_nuevo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
      

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge